### ISSUE TITLE
files not transferring over from build

### ISSUE THREAD

**Issue by MdDakota** [tomek-l/jetson-cameras#1]
Hey, I am new to python and coding in general. 
The problem I am running into is that when I've got everything downloaded and I try to run main.py it comes up with-

File "main.py", line 13, in <module>
    from rgb import RGBThread
  File "/home/therm3/ai-thermometer/rgb/__init__.py", line 1, in <module>
    from .rgb_thread import *
  File "/home/therm3/ai-thermometer/rgb/rgb_thread.py", line 7, in <module>
    from .camera import make_imx219_capture

When I look in my camera directory there are no files. Am I missing something on the download? or will I have to add the files in afterwards?

**Comment by rtime2awaken** [comment]
I'm having the same issue.  I see that some of the files are hidden.  I don't know if that has anything to do with it.  I also don't know w if these issues will be seen from this location.  I am new to github.

**Comment by tomasz-lewicki** [comment]
Hi! See if [this](https://github.com/tomek-l/ai-thermometer/issues/35) helps :slightly_smiling_face:
